name: segmented_progress_bar
description: A segmented progress bar that can display multiple progress bars with different levels of progressions
version: 0.0.1
homepage:
repository: https://github.com/ashishbeck/segmented_progress_bar

environment:
  sdk: '>=2.18.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.0.0

flutter:
